version: '3'
services:
  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
      args:
        UIDUser: ${ENV_UID_USER}
        GIDGroup: ${ENV_GID_GROUP}
    working_dir: ${ENV_WORKING_DIR}
    volumes:
      - ../:${ENV_WORKING_DIR}
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      #- ./xdebug.log:/tmp/xdebug.log
    environment:
      - "DB_PORT=${ENV_DB_PORT}"
      - "DB_HOST=${ENV_DB_HOST}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_pruebalaravelblog

  # Al final no creo q lo use.
  # Servidor NodeJs para comandos de laravel.
  nodejs:
    build:
      context: ./
      dockerfile: node.dockerfile
      args:
        UIDUser: ${ENV_UID_USER}
        GIDGroup: ${ENV_GID_GROUP}
    working_dir: ${ENV_WORKING_DIR}
    ports:
        - ${ENV_EXPOSE_NODE_3000_PORT}:3000
        - ${ENV_EXPOSE_NODE_3001_PORT}:3001
    volumes:
      - ../:${ENV_WORKING_DIR}
    networks:
      - app_pruebalaravelblog

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
      args:
        UIDUser: ${ENV_UID_USER}
        GIDGroup: ${ENV_GID_GROUP}
    working_dir: ${ENV_WORKING_DIR}
    volumes:
      - ../:${ENV_WORKING_DIR}
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${ENV_EXPOSE_WEB_PORT}:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_pruebalaravelblog

  # The Database
  database:
    image: mariadb
    volumes:
      - dbdata_pruebalaravelblog:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${ENV_MYSQL_DATABASE}"
      - "MYSQL_USER=${ENV_MYSQL_USER}"
      - "MYSQL_PASSWORD=${ENV_MYSQL_PASSWORD}"

    ports:
        - "${ENV_EXPOSE_DB_PORT}:${ENV_DB_PORT}"
    networks:
      - app_pruebalaravelblog


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=database
     - PMA_USER=root
     - "PMA_PASSWORD=${ENV_MYSQL_PASSWORD}"
     - UPLOAD_LIMIT=300M

    ports:
     - "${ENV_EXPOSE_PHPMYADMIN_PORT}:80"
    volumes:
     - /sessions
    # Defino que phpmyadmin, depende de estos dos servicios, para q se inciie despues de ellos. No se garantizan que hayan terminado. (puede q realmente no haga falta)
    depends_on:
      - app
      - database
    networks:
      - app_pruebalaravelblog

# mailhog: https://styde.net/capturando-emails-de-forma-local-con-mailhog-y-laravel-homestead/
# Es un container que sustituye al mailtrap.
# Dejo pendiente configurarlo
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${ENV_EXPOSE_MAILHOG_1025_PORT}:1025
      - ${ENV_EXPOSE_MAILHOG_8025_PORT}:8025
    networks:
      - app_pruebalaravelblog

volumes:
  dbdata_pruebalaravelblog:

networks:
  app_pruebalaravelblog:
